name: Build and Deploy PAWW

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  build-snapshot:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Build Snapshot iOS
        run: |
          cd mobile-app
          APP_ENV=snapshot eas build --profile snapshot --platform ios --non-interactive

      - name: Build Snapshot Android
        run: |
          cd mobile-app
          APP_ENV=snapshot eas build --profile snapshot --platform android --non-interactive

  build-production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Build Production iOS
        run: |
          cd mobile-app
          APP_ENV=production eas build --profile production --platform ios --non-interactive

      - name: Build Production Android
        run: |
          cd mobile-app
          APP_ENV=production eas build --profile production --platform android --non-interactive

      - name: Submit to App Store
        if: success()
        run: |
          cd mobile-app
          eas submit --platform ios --profile production --non-interactive

      - name: Submit to Play Store
        if: success()
        run: |
          cd mobile-app
          eas submit --platform android --profile production --non-interactive 